# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Yihuawenxin\Yihuawenxinui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 171, 64))
        self.label.setStyleSheet("image: url(:/pi/fuck_test_2.png);\n"
"color: rgb(255, 255, 255);\n"
"background-color: #970804;\n"
"font: 18pt \"楷体\";\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget_1 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_1.setGeometry(QtCore.QRect(0, 64, 164, 536))
        self.listWidget_1.setStyleSheet("QListView {\n"
"    \n"
"    background-color: rgb(88, 15, 5);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:40px;\n"
"padding-left:4px;\n"
"\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color:  transparent;\n"
"    color: #dfbe96;\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"background-color:  transparent;\n"
"color: #dfbe96;\n"
"\n"
"border-left: 2px solid #ffffff;\n"
"}\n"
"QListWidget::item:hover {\n"
"    border-left: 2px solid white;\n"
"}")
        self.listWidget_1.setObjectName("listWidget_1")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/魔方_cube-five.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/三菱_mitsubishi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/六边立体_hexagonal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/三棱锥_triangular-pyramid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget_1.addItem(item)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(164, 64, 836, 536))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.button_2 = QtWidgets.QPushButton(self.page_1)
        self.button_2.setGeometry(QtCore.QRect(580, 410, 100, 40))
        self.button_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}")
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.page_1)
        self.button_1.setGeometry(QtCore.QRect(180, 410, 100, 40))
        self.button_1.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.button_1.setObjectName("button_1")
        self.imglabel_1_2 = QtWidgets.QLabel(self.page_1)
        self.imglabel_1_2.setGeometry(QtCore.QRect(470, 180, 330, 200))
        self.imglabel_1_2.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"")
        self.imglabel_1_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.imglabel_1_2.setObjectName("imglabel_1_2")
        self.imglabel_1_1 = QtWidgets.QLabel(self.page_1)
        self.imglabel_1_1.setGeometry(QtCore.QRect(70, 180, 330, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.imglabel_1_1.setFont(font)
        self.imglabel_1_1.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;")
        self.imglabel_1_1.setTextFormat(QtCore.Qt.PlainText)
        self.imglabel_1_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.imglabel_1_1.setObjectName("imglabel_1_1")
        self.label_11 = QtWidgets.QLabel(self.page_1)
        self.label_11.setGeometry(QtCore.QRect(360, 200, 150, 150))
        self.label_11.setStyleSheet("image: url(:/pi/fuck_test_1.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.listView = QtWidgets.QListView(self.page_1)
        self.listView.setGeometry(QtCore.QRect(0, 0, 836, 536))
        self.listView.setStyleSheet("background-image: url(:/pi/ljz_2.png);\n"
"background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.setGeometry(QtCore.QRect(280, 60, 291, 91))
        self.label_3.setStyleSheet("image: url(:/pi/微信图片_20230412225934.png);\n"
"font: 14pt \"楷体\";\n"
"color: rgb(223, 190, 150);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.listView.raise_()
        self.button_2.raise_()
        self.button_1.raise_()
        self.imglabel_1_2.raise_()
        self.imglabel_1_1.raise_()
        self.label_11.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.listView_5 = QtWidgets.QListView(self.page_2)
        self.listView_5.setGeometry(QtCore.QRect(0, 0, 1000, 541))
        self.listView_5.setStyleSheet("background-image: url(:/pi/ljz_2.png);\n"
"background-color: rgb(255, 255, 255);")
        self.listView_5.setObjectName("listView_5")
        self.button_13 = QtWidgets.QPushButton(self.page_2)
        self.button_13.setGeometry(QtCore.QRect(180, 410, 100, 40))
        self.button_13.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}")
        self.button_13.setObjectName("button_13")
        self.imglabel_2_2 = QtWidgets.QLabel(self.page_2)
        self.imglabel_2_2.setGeometry(QtCore.QRect(470, 180, 330, 200))
        self.imglabel_2_2.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"")
        self.imglabel_2_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.imglabel_2_2.setObjectName("imglabel_2_2")
        self.button_14 = QtWidgets.QPushButton(self.page_2)
        self.button_14.setGeometry(QtCore.QRect(580, 410, 100, 40))
        self.button_14.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}")
        self.button_14.setObjectName("button_14")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(270, 50, 311, 131))
        self.label_5.setStyleSheet("image: url(:/pi/微信图片_20230412225930.png);\n"
"font: 14pt \"楷体\";\n"
"color: rgb(223, 190, 150);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_28 = QtWidgets.QLabel(self.page_2)
        self.label_28.setGeometry(QtCore.QRect(360, 200, 150, 150))
        self.label_28.setStyleSheet("image: url(:/pi/背景2.png);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setGeometry(QtCore.QRect(70, 180, 330, 200))
        self.textEdit.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;")
        self.textEdit.setObjectName("textEdit")
        self.listView_5.raise_()
        self.button_13.raise_()
        self.imglabel_2_2.raise_()
        self.button_14.raise_()
        self.label_5.raise_()
        self.textEdit.raise_()
        self.label_28.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.button_19 = QtWidgets.QPushButton(self.page_3)
        self.button_19.setGeometry(QtCore.QRect(180, 410, 100, 40))
        self.button_19.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}")
        self.button_19.setObjectName("button_19")
        self.imglabel__3_1 = QtWidgets.QLabel(self.page_3)
        self.imglabel__3_1.setGeometry(QtCore.QRect(470, 180, 330, 200))
        self.imglabel__3_1.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"")
        self.imglabel__3_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.imglabel__3_1.setObjectName("imglabel__3_1")
        self.button_20 = QtWidgets.QPushButton(self.page_3)
        self.button_20.setGeometry(QtCore.QRect(580, 410, 100, 40))
        self.button_20.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #a0a0a0;\n"
"    border-style: inset;\n"
"}")
        self.button_20.setObjectName("button_20")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(280, 60, 291, 91))
        self.label_8.setStyleSheet("image: url(:/pi/微信图片_20230412225934.png);\n"
"font: 14pt \"楷体\";\n"
"color: rgb(223, 190, 150);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.imglabel_3_1 = QtWidgets.QLabel(self.page_3)
        self.imglabel_3_1.setGeometry(QtCore.QRect(70, 180, 330, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.imglabel_3_1.setFont(font)
        self.imglabel_3_1.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;")
        self.imglabel_3_1.setTextFormat(QtCore.Qt.PlainText)
        self.imglabel_3_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.imglabel_3_1.setObjectName("imglabel_3_1")
        self.label_33 = QtWidgets.QLabel(self.page_3)
        self.label_33.setGeometry(QtCore.QRect(360, 200, 161, 150))
        self.label_33.setStyleSheet("image: url(:/pi/背景3.png);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.listView_10 = QtWidgets.QListView(self.page_3)
        self.listView_10.setGeometry(QtCore.QRect(0, 0, 836, 536))
        self.listView_10.setStyleSheet("background-image: url(:/pi/ljz_2.png);\n"
"background-color: rgb(255, 255, 255);")
        self.listView_10.setObjectName("listView_10")
        self.listView_10.raise_()
        self.imglabel__3_1.raise_()
        self.button_19.raise_()
        self.button_20.raise_()
        self.imglabel_3_1.raise_()
        self.label_8.raise_()
        self.label_33.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.listView_11 = QtWidgets.QListView(self.page_4)
        self.listView_11.setGeometry(QtCore.QRect(0, 0, 836, 536))
        self.listView_11.setStyleSheet("background-image: url(:/pi/ljz_2.png);\n"
"background-color: rgb(255, 255, 255);")
        self.listView_11.setObjectName("listView_11")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(130, 60, 521, 81))
        self.label_9.setStyleSheet("font: 12pt \"楷体\";")
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setGeometry(QtCore.QRect(130, 110, 521, 81))
        self.label_12.setStyleSheet("font: 12pt \"楷体\";")
        self.label_12.setObjectName("label_12")
        self.label_34 = QtWidgets.QLabel(self.page_4)
        self.label_34.setGeometry(QtCore.QRect(130, 160, 661, 81))
        self.label_34.setStyleSheet("font: 12pt \"楷体\";")
        self.label_34.setObjectName("label_34")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser.setGeometry(QtCore.QRect(150, 240, 551, 211))
        self.textBrowser.setStyleSheet("    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font-family: \"微软雅黑\";\n"
"    box-shadow: 2px 2px 4px #888888;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_35 = QtWidgets.QLabel(self.page_4)
        self.label_35.setGeometry(QtCore.QRect(730, 60, 71, 61))
        self.label_35.setStyleSheet("image: url(:/pi/微信图片_20230412225924.png);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_4)
        self.label_36.setGeometry(QtCore.QRect(320, 470, 211, 41))
        self.label_36.setStyleSheet("image: url(:/pi/微信图片_20230412225900.png);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.stackedWidget.addWidget(self.page_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(164, 0, 836, 64))
        self.label_2.setStyleSheet("background-color: #970804;\n"
"font: 16pt \"楷体\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "艺画文心"))
        self.label.setText(_translate("MainWindow", "艺画文心"))
        __sortingEnabled = self.listWidget_1.isSortingEnabled()
        self.listWidget_1.setSortingEnabled(False)
        item = self.listWidget_1.item(0)
        item.setText(_translate("MainWindow", "丹青流转"))
        item = self.listWidget_1.item(1)
        item.setText(_translate("MainWindow", "墨韵生花"))
        item = self.listWidget_1.item(2)
        item.setText(_translate("MainWindow", "彩墨婆娑"))
        item = self.listWidget_1.item(3)
        item.setText(_translate("MainWindow", "介绍和帮助"))
        self.listWidget_1.setSortingEnabled(__sortingEnabled)
        self.button_2.setText(_translate("MainWindow", "下载"))
        self.button_1.setText(_translate("MainWindow", "运行"))
        self.imglabel_1_2.setText(_translate("MainWindow", "生成图片"))
        self.imglabel_1_1.setText(_translate("MainWindow", "拖拽放入图片"))
        self.label_3.setText(_translate("MainWindow", "丹青流转"))
        self.button_13.setText(_translate("MainWindow", "运行"))
        self.imglabel_2_2.setText(_translate("MainWindow", "生成图片"))
        self.button_14.setText(_translate("MainWindow", "下载"))
        self.label_5.setText(_translate("MainWindow", "墨韵生花"))
        self.button_19.setText(_translate("MainWindow", "运行"))
        self.imglabel__3_1.setText(_translate("MainWindow", "生成图片"))
        self.button_20.setText(_translate("MainWindow", "下载"))
        self.label_8.setText(_translate("MainWindow", "彩墨婆娑"))
        self.imglabel_3_1.setText(_translate("MainWindow", "拖拽放入图片"))
        self.label_9.setText(_translate("MainWindow", "丹青流转：基于 CycleGAN等循环生成对抗模型的中国山水画的山水画皱法风格迁移模块"))
        self.label_12.setText(_translate("MainWindow", "墨韵生花：基于Stable Diffusion 扩散模型的文字生成中国山水画模块"))
        self.label_34.setText(_translate("MainWindow", "彩墨婆娑：基于Stable Diffusion 扩散模型的中国山水画图像上色模块以及基于卷积神经网络的图像风格转换模块"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    欢迎大家来到本团队开发的“艺画文心——中国传统艺术绘画创作系统”，为了传承发扬中国传统，让更多人爱上山水画，本团队开发这款软件。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    使用“丹青流转”、“彩墨婆娑”的时候，需要将待处理的图片的拖住放入左边的框中，点击运行按钮，等待一段一分钟左右的处理时间后，生成的图片会显示在右边的框中，点击下载按钮即可保存生成的图片。  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">      使用“墨韵生花”时，需要在左边的文本输入框，输入您想要生成的图片的描述，点击运行，等待一段时间，生成的图片将会显示在右边，点击下载按钮即可保存</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "中国传统艺术绘画AI创作系统"))
import img_rc
